/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  home: [
    'index',
    { type: 'html', value: 'Mario', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'Mario' },
    { type: 'html', value: 'Kart', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'Kart' },
    { type: 'html', value: 'Sonic', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'Sonic' },
    { type: 'html', value: 'Souls', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'Souls' },
    { type: 'html', value: 'Platformer', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'Platformer' },
    { type: 'html', value: 'Shooter', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'Shooter' },
    { type: 'html', value: 'RPG', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'RPG' },
    { type: 'html', value: 'MOBA', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'MOBA' },
    { type: 'html', value: 'MMO', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'MMO' },
    { type: 'html', value: 'Adventure', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'Adventure' },
    { type: 'html', value: 'Party', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'Party' },
    { type: 'html', value: 'The rest', className: 'sidebar-title', },
    { type: 'autogenerated', dirName: 'The rest' },
  ]
};

module.exports = sidebars;